const products = [
    // {
    //     id: 1,
    //     name: 'Object',
    //     short_description: 'Short description here',
    //     description: 'Long description here',
    //     price: 9999,
    //     image: '/path/to/img',
    //     category: 'category',
    // },
    {
        id: 1,
        name: 'Convertible car',
        short_description: 'Who needs a roof anyway',
        description: 'The sun is shining, the weather is sweet',
        price: 35000.00,
        image: 'cabriolet.png',
        category: 'cars',
    },
    {
        id: 2,
        name: 'Camera',
        short_description: 'Takes photos',
        description: 'Takes some really nice photos during daytime only because it does not have a flash',
        price: 149.99,
        image: 'camera-dslr.png',
        category: 'cameras',
    },
    {
        id: 3,
        name: 'Camera with Flash',
        short_description: 'Takes lit up photos',
        description: 'Takes some really nice photos during daytime or nighttime',
        price: 249.99,
        image: 'camera-flash.png',
        category: 'cameras',
    },
    {
        id: 4,
        name: 'Fast car',
        short_description: 'Car goes wroom',
        description: 'Wroom wroom, this car will take you very far',
        price: 20000.00,
        image: 'car-fast.png',
        category: 'cars',
    },
    {
        id: 5,
        name: 'Slow car',
        short_description: 'Car goes beep beep',
        description: 'Beep, a car for city driving',
        price: 12000.00,
        image: '/car-slow.png',
        category: 'cars',
    },
    {
        id: 6,
        name: 'Doge',
        short_description: 'Woof',
        description: 'Woof woof bark bark',
        price: 200.00,
        image: 'doge.png',
        category: 'pets',
    },
    {
        id: 7,
        name: 'Cat',
        short_description: 'Meow',
        description: 'Likes to dance right meow',
        price: 100.00,
        image: 'cat.png',
        category: 'pets',
    },
    {
        id: 8,
        name: 'Parrot',
        short_description: 'It flies!',
        description: 'It will also try to talk to you, maybe.',
        price: 60.00,
        image: 'parrot.png',
        category: 'pets',
    },
    {
        id: 9,
        name: 'Flower',
        short_description: 'Colorful and flowery',
        description: 'Woof woof bark bark',
        price: 25.00,
        image: 'flower.png',
        category: 'plants',
    },
    {
        id: 10,
        name: 'Green plant',
        short_description: 'Is very green',
        description: 'Produces plenty of oxygen because it is so very green',
        price: 12.00,
        image: 'plant.png',
        category: 'plants',
    },
    {
        id: 11,
        name: 'Cactus',
        short_description: 'Ouch!',
        description: 'Spiky, green and full of water',
        price: 15.00,
        image: 'cactus.png',
        category: 'plants',
    },
    {
        id: 12,
        name: 'Squished Shibe',
        short_description: 'Not walk. Very tire fren! Plez stahp!',
        description: 'Not walk. Very tire fren! Plez stahp!',
        price: 1750.00,
        image: 'squished-shibe.png',
        category: 'pets',
    },
];

const categories = [
    {
        id: 'cars',
        name: 'Cars',
    },
    {
        id: 'cameras',
        name: 'Cameras',
    },
    {
        id: 'food',
        name: `Food 'n Stuff`,
    },
    {
        id: 'plants',
        name: 'Plants',
    },
    {
        id: 'pets',
        name: 'Pets',
    },
];

export default {
    categories,
    products,
};
